<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-12-14T06:59:59Z" name="Default suite" finished-at="2021-12-14T07:00:24Z" duration-ms="24423">
    <groups>
    </groups>
    <test started-at="2021-12-14T06:59:59Z" name="Default test" finished-at="2021-12-14T07:00:24Z" duration-ms="24423">
      <class name="SeleniumTesting.AEMhdfc.HomepageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:SeleniumTesting.AEMhdfc.HomepageTest@115667d]" started-at="2021-12-14T12:29:59Z" name="setUp" finished-at="2021-12-14T12:30:04Z" duration-ms="4830" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyHeader()[pri:1, instance:SeleniumTesting.AEMhdfc.HomepageTest@115667d]" started-at="2021-12-14T12:30:04Z" name="verifyHeader" finished-at="2021-12-14T12:30:23Z" duration-ms="19398" status="FAIL">
          <exception class="java.net.MalformedURLException">
            <message>
              <![CDATA[unknown protocol: tel]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.net.MalformedURLException: unknown protocol: tel
	at java.base/java.net.URL.<init>(URL.java:681)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at PageObjects.Homepage.verifyHeaderLinks(Homepage.java:722)
	at SeleniumTesting.AEMhdfc.HomepageTest.verifyHeader(HomepageTest.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.net.MalformedURLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHeader -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumTesting.AEMhdfc.HomepageTest@115667d]" started-at="2021-12-14T12:30:23Z" name="tearDown" finished-at="2021-12-14T12:30:24Z" duration-ms="181" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- SeleniumTesting.AEMhdfc.HomepageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
